### ISSUE TITLE
fio hang

### ISSUE THREAD

**Issue by lizengwu** [axboe/fio#1852]
**Please acknowledge the following before creating a ticket**

- [ ] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
Use fio pressure test, fio parameter --runtime fixed 30s, bs numjobs will switch different values, after a period of time will occasionally fio hang

**FIO process info:**
root@localhost:/tmp# ps -ef | grep fio
root         688       2  0 Jan03 ?        00:00:00 [vfio-irqfd-clea]
root        3199       1  0 Jan03 ?        00:05:49 fio --bs=1M --direct=1 --runtime=30 --rw=read --iodepth=1 --time_based --group_reporting --randrepeat=0 --norandommap --ioengine=libaio --name=vdb_iops --filename=/dev/vdb --numjobs=3
root        3282    3199  0 Jan03 ?        00:00:00 fio --bs=1M --direct=1 --runtime=30 --rw=read --iodepth=1 --time_based --group_reporting --randrepeat=0 --norandommap --ioengine=libaio --name=vdb_iops --filename=/dev/vdb --numjobs=3
root      148228  137697  0 03:19 pts/0    00:00:00 grep --color=auto fio

**starce info:**
root@localhost:~# strace -f -p 3282
strace: Process 3282 attached
io_getevents(0x7fe872604000, 1, 1, 

starce -f -p 3199 output:
[pid  3199] newfstatat(AT_FDCWD, "/tmp/fio-dump-status", 0x7fffab340160, 0) = -1 ENOENT (No such file or directory)
[pid  3199] clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000}, NULL) = 0
[pid  3199] wait4(3282, 0x7fffab3411d4, WNOHANG, NULL) = 0
[pid  3199] newfstatat(AT_FDCWD, "/tmp/fio-dump-status", 0x7fffab340160, 0) = -1 ENOENT (No such file or directory)
[pid  3199] clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000}, NULL) = 0
[pid  3199] wait4(3282, 0x7fffab3411d4, WNOHANG, NULL) = 0
[pid  3199] newfstatat(AT_FDCWD, "/tmp/fio-dump-status", 0x7fffab340160, 0) = -1 ENOENT (No such file or directory)
[pid  3199] clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000}, NULL) = 0
[pid  3199] wait4(3282, 0x7fffab3411d4, WNOHANG, NULL) = 0
[pid  3199] newfstatat(AT_FDCWD, "/tmp/fio-dump-status", 0x7fffab340160, 0) = -1 ENOENT (No such file or directory)
[pid  3199] clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000}, NULL) = 0
[pid  3199] wait4(3282, 0x7fffab3411d4, WNOHANG, NULL) = 0
[pid  3199] newfstatat(AT_FDCWD, "/tmp/fio-dump-status", 0x7fffab340160, 0) = -1 ENOENT (No such file or directory)
[pid  3199] clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000}, NULL) = 0
[pid  3199] wait4(3282, 0x7fffab3411d4, WNOHANG, NULL) = 0
[pid  3199] newfstatat(AT_FDCWD, "/tmp/fio-dump-status", 0x7fffab340160, 0) = -1 ENOENT (No such file or directory)
[pid  3199] clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000}, NULL) = 0
[pid  3199] wait4(3282, 0x7fffab3411d4, WNOHANG, NULL) = 0
[pid  3199] newfstatat(AT_FDCWD, "/tmp/fio-dump-status", 0x7fffab340160, 0) = -1 ENOENT (No such file or directory)
[pid  3199] clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000}, NULL) = 0
[pid  3199] wait4(3282, 0x7fffab3411d4, WNOHANG, NULL) = 0
[pid  3199] newfstatat(AT_FDCWD, "/tmp/fio-dump-status", 0x7fffab340160, 0) = -1 ENOENT (No such file or directory)
[pid  3199] clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000}, NULL) = 0
[pid  3199] wait4(3282, 0x7fffab3411d4, WNOHANG, NULL) = 0
[pid  3199] newfstatat(AT_FDCWD, "/tmp/fio-dump-status", 0x7fffab340160, 0) = -1 ENOENT (No such file or directory)
[pid  3199] clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000}, NULL) = 0
[pid  3199] wait4(3282, 0x7fffab3411d4, WNOHANG, NULL) = 0
[pid  3199] newfstatat(AT_FDCWD, "/tmp/fio-dump-status", 0x7fffab340160, 0) = -1 ENOENT (No such file or directory)
[pid  3199] clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000}, NULL) = 0
[pid  3199] wait4(3282, 0x7fffab3411d4, WNOHANG, NULL) = 0
[pid  3199] newfstatat(AT_FDCWD, "/tmp/fio-dump-status", 0x7fffab340160, 0) = -1 ENOENT (No such file or directory)
[pid  3199] clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000}, NULL) = 0
[pid  3199] wait4(3282, 0x7fffab3411d4, WNOHANG, NULL) = 0
[pid  3199] newfstatat(AT_FDCWD, "/tmp/fio-dump-status", 0x7fffab340160, 0) = -1 ENOENT (No such file or directory)
[pid  3199] clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000}, NULL) = 0
[pid  3199] wait4(3282, 0x7fffab3411d4, WNOHANG, NULL) = 0
[pid  3199] newfstatat(AT_FDCWD, "/tmp/fio-dump-status", 0x7fffab340160, 0) = -1 ENOENT (No such file or directory)

**Environment**: 
ubuntu 22.04 LTS 5.15.0-127-generic
**fio version**: 
fio-3.28
**Reproduction steps**

**Comment by lizengwu** [comment]
> size

runtime

**Comment by sitsofe** [comment]
@lizengwu does the problem happen if fix the numjobs to 2? If so does it happen when numjobs is fixed to 1?

**Comment by vincentkfu** [comment]
You are using fio 3.28 which was released years ago. Please try a current version.

**Comment by lizengwu** [comment]
> You are using fio 3.28 which was released years ago. Please try a current version.
Thank you for your reply.
It can still be reproduced according to the script based on versions 3.35 and 3.38. With the block size (bs) fixed at 1M, the probability of reproduction is quite high. 
**error info:**
Running test: fio_test_bs_1M_numjobs_3_iodepth_1                                                                                                                                                                                    
fio: set debug option process                                                                                                                                                                                                       
fio: set debug option mutex                                                                                                                                                                                                         
fio: missing job number                                                                                                                                                                                                             
fio_test_bs_1M_numjobs_3_iodepth_1: (g=0): rw=randwrite, bs=(R) 1024KiB-1024KiB, (W) 1024KiB-1024KiB, (T) 1024KiB-1024KiB, ioengine=libaio, iodepth=1                                                                               
...                                                                                                                                                                                                                                 
fio-3.38                                                                                                                                                                                                                            
mutex    5717  wait on startup_sem                                                                                                                                                                                                  
mutex    5717  done waiting on startup_sem                                                                                                                                                                                          
Starting 3 processes                                                                                                                                                                                                                
process  5717  pid=0: runstate NOT_CREATED -> SETTING_UP                                                                                                                                                                            
process  5717  pid=0: runstate SETTING_UP -> NOT_CREATED                                                                                                                                                                            
process  5717  pid=0: runstate NOT_CREATED -> SETTING_UP                                                                                                                                                                            
process  5717  pid=0: runstate SETTING_UP -> NOT_CREATED                                                                                                                                                                            
process  5717  pid=0: runstate NOT_CREATED -> SETTING_UP                                                                                                                                                                            
process  5717  pid=0: runstate SETTING_UP -> NOT_CREATED                                                                                                                                                                            
process  5717  pid=0: runstate NOT_CREATED -> CREATED                                                                                                                                                                               
process  5717  will fork                                                                                                                                                                                                            
mutex    5717  wait on startup_sem                                                                                                                                                                                                  
process  5768  jobs pid=5768 started                                                                                                                                                                                                
process  5768  pid=5768: runstate CREATED -> INITIALIZED                                                                                                                                                                            
mutex    5768  up startup_sem                                                                                                                                                                                                       
mutex    5768  wait on td->sem                                                                                                                                                                                                      
mutex    5717  done waiting on startup_sem                                                                                                                                                                                          
process  5717  pid=0: runstate NOT_CREATED -> CREATED                                                                                                                                                                               
process  5717  will fork                                                                                                                                                                                                            
mutex    5717  wait on startup_sem                                                                                                                                                                                                  
process  5769  jobs pid=5769 started                                                                                                                                                                                                
process  5769  pid=5769: runstate CREATED -> INITIALIZED
mutex    5769  up startup_sem
mutex    5769  wait on td->sem
mutex    5717  done waiting on startup_sem
process  5717  pid=0: runstate NOT_CREATED -> CREATED
process  5717  will fork
mutex    5717  wait on startup_sem
process  5770  jobs pid=5770 started
process  5770  pid=5770: runstate CREATED -> INITIALIZED
mutex    5770  up startup_sem
mutex    5770  wait on td->sem
mutex    5717  done waiting on startup_sem
process  5717  pid=5768: runstate INITIALIZED -> RUNNING
process  5717  pid=5769: runstate INITIALIZED -> RUNNING
mutex    5768  done waiting on td->sem
process  5717  pid=5770: runstate INITIALIZED -> RUNNING
mutex    5769  done waiting on td->sem
mutex    5770  done waiting on td->sem
Jobs: 3 (f=3): [w(3)][73.3%][w=7652MiB/s][w=7652 IOPS][eta 00m:08s]
process  5770  pid=5770: runstate RUNNING -> FINISHING][eta 00m:00s]
process  5768  pid=5768: runstate RUNNING -> FINISHING
process  5770  pid=5770: runstate FINISHING -> EXITED
process  5768  pid=5768: runstate FINISHING -> EXITED
process  5717  pid=5768: runstate EXITED -> REAPED
process  5717  pid=5770: runstate EXITED -> REAPED
Jobs: 1 (f=1): [_(1),w(1),_(1)][100.0%][eta 00m:00s]
Jobs: 1 (f=1): [_(1),w(1),_(1)][100.0%][eta 00m:00s]
Jobs: 1 (f=1): [_(1),w(1),_(1)][100.0%][eta 00m:00s]
Jobs: 1 (f=1): [_(1),w(1),_(1)][100.0%][eta 00m:00s]
Jobs: 1 (f=1): [_(1),w(1),_(1)][100.0%][eta 00m:00s]
Jobs: 1 (f=1): [_(1),w(1),_(1)][100.0%][eta 00m:00s]

[root@33-166 ~]# ps -aux | grep fio
root        1977  0.0  0.0      0     0 ?        I<   19:39   0:00 [vfio-irqfd-clea]
root        5717  0.2  0.0 258624  6384 pts/3    Sl+  19:57   0:01 /root/seasan/fio-fio-3.38/fio --name=fio_test_bs_1M_numjobs_3_iodepth_1 --filename=/dev/vda --bs=1M --ioengine=libaio --userspace_reap --rw=randwrite --direct=1 --numjobs=3 --iodepth=1 --time_based --eta-newline=20 --runtime=30 --group_reporting --debug=process mutex job
root        5769  0.6  0.0 194136  3920 ?        Ss   19:57   0:02 /root/seasan/fio-fio-3.38/fio --name=fio_test_bs_1M_numjobs_3_iodepth_1 --filename=/dev/vda --bs=1M --ioengine=libaio --userspace_reap --rw=randwrite --direct=1 --numjobs=3 --iodepth=1 --time_based --eta-newline=20 --runtime=30 --group_reporting --debug=process mutex job
root        5845  0.0  0.0  12136  1148 pts/1    S+   20:04   0:00 grep --color=auto fio
[root@33-166 ~]# 
[root@33-166 ~]# 
[root@33-166 ~]# strace -f -p 5769
strace: Process 5769 attached
io_getevents(0x7fe21be1d000, 1, 1,

[root@33-166 fio-fio-3.38]# ldd fio
        linux-vdso.so.1 (0x00007ffe413bd000)
        libnuma.so.1 => /lib64/libnuma.so.1 (0x00007fd01005e000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fd00fe56000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fd00fc3f000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd00fa1f000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fd00f69d000)
        libmvec.so.1 => /lib64/libmvec.so.1 (0x00007fd00f472000)
        libaio.so.1 => /lib64/libaio.so.1 (0x00007fd00f26f000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fd00f06b000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fd00eca6000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd01026a000)

[root@33-166 fio-fio-3.38]# uname -r
4.18.0-348.7.1.el8_5.x86_64

[root@33-166 fio-fio-3.38]# cat /sys/block/vda/queue/max_segments
32
[root@33-166 fio-fio-3.38]# cat /sys/block/vda/queue/max_segment_size 
65536
[root@33-166 fio-fio-3.38]# cat /sys/block/vda/inflight 
       0        0
[root@33-166 fio-fio-3.38]# 


[root@33-166 fio-fio-3.38]# iostat -x 1 /dev/vda
Linux 4.18.0-348.7.1.el8_5.x86_64 (33-166)      01/08/2025      _x86_64_        (48 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.24    0.00    0.19    0.00    0.00   99.56

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
vda               0.00    19.17    2.47 8837.77    50.18 3103270.94   702.09    16.98    1.92    0.03    1.92   0.06  52.16

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.00    0.00    0.04    0.00    0.00   99.96

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
vda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.00    0.00    0.00    0.00    0.00  100.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
vda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.00    0.00    0.02    0.00    0.00   99.98

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
vda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.02    0.00    0.00    0.00    0.00   99.98

**Comment by lizengwu** [comment]
when error occurs， inflight IO info：
[root@33-166 ~]# cat /sys/kernel/debug/block/vda/hctx*/dispatch
00000000eed06c05 {.op=WRITE, .cmd_flags=SYNC|IDLE, .rq_flags=IO_STAT|STATS, .state=idle, .tag=39, .internal_tag=-1}

**Comment by sitsofe** [comment]
@lizengwu can you pare back your script and options further? To start looking at this we really need the bare minimum that makes the issue happen. For example:
- Can you fix the iodepth to a specific value?
- Does the problem continue happening without the ` --userspace_reap` option?
- Can you fix the block size?
- Does the problem still happen without `direct=1`?

Is there anything in `dmesg` when the hang occurs?

**Comment by lizengwu** [comment]
> @lizengwu can you pare back your script and options further? To start looking at this we really need the bare minimum that makes the issue happen. For example:
> 
> * Can you fix the iodepth to a specific value?
> * Does the problem continue happening without the ` --userspace_reap` option?
> * Can you fix the block size?
> * Does the problem still happen without `direct=1`?
> 
> Is there anything in `dmesg` when the hang occurs?

Can you fix the iodepth to a specific value?
I will try this.

Does the problem continue happening without the ` --userspace_reap` option?
without --userspace_reap, fio hang still occur.

Can you fix the block size?
block size is fixed to 1M now.

Does the problem still happen without `direct=1`?
I will try.

Is there anything in `dmesg` when the hang occurs?
there is noting info related for this error in dmesg.


Io schduler default is none, error will occur smaller than 4h， I set to mq-deadline, fio is running 12h+ normally .
[root@33-166 queue]# cat /sys/block/vda/queue/scheduler 
[mq-deadline] kyber bfq none

**Comment by sitsofe** [comment]
> Io schduler default is none, error will occur smaller than 4h， I set to mq-deadline, fio is running 12h+ normally .

That does sound suspicious and makes it more likely that this is a kernel bug. You mentioned your kernel is 4.18.0-348.7.1.el8_5.x86_64, can you try seeing if the issue is happening in at least a 6.x kernel (you may have to use a different distro version if there are no newer kernels for your current release)?

**Comment by lizengwu** [comment]
> > Io schduler default is none, error will occur smaller than 4h， I set to mq-deadline, fio is running 12h+ normally .
> 
> That does sound suspicious and makes it more likely that this is a kernel bug. You mentioned your kernel is 4.18.0-348.7.1.el8_5.x86_64, can you try seeing if the issue is happening in at least a 6.x kernel (you may have to use a different distro version if there are no newer kernels for your current release)?

Thanks for your reply.

this is a kernel bug，the bug reason is analyzing.

thank you all for your help, i will close this issue.
