### ISSUE TITLE
clock setaffinity failed on solaris

### ISSUE THREAD

**Issue by mattkirby** [axboe/fio#46]
When running fio-2.2.5-3-g209e on solaris 11.2 I receive the message clock setaffinity failed. I disabled HTT to ensure it was not interfering, but the results persist. I get the same error whether testing within a virtual machine, or on bare metal. I'm running on a pair of Intel E5-2640s. When I build the same version on debian the issue is not present so I wonder whether it's related to solaris 11.2. In any case, any suggestions on whether there's anything I can try, or whether this may be due to an issue with fio and solaris 11, are greatly appreciated.

Please let me know if I can provide any additional information.

**Comment by axboe** [comment]
Can you try with current -git? I just added a patch to expand that error a little bit, so we can get some more clues. In reality, it wont matter, fio will just use the other time sources. But it would be nice to find out why it's failing, at least.

**Comment by axboe** [comment]
OK, I think I see what it is. Update to current -git and re-run, should fix the issue for you.

**Comment by mattkirby** [comment]
Thank you for the quick response.

When I build from master now I receive this error:
`gettime.c: In function ‘clock_thread_fn’:
gettime.c:483:10: warning: ‘__err’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   log_err("clock cpuset init failed: %s\n", strerror(__err));
          ^`

When running `fio --cpuclock-test` it fails reporting a few different messages. This failed before too, but the messages were consistent. Here are the new messages:
`clock setaffinity failed: Operation not supported
clock setaffinity failed: No such process
clock setaffinity failed: Invalid argument`

**Comment by axboe** [comment]
Gah, thinko on my part, checked in a fix for that now.

**Comment by dankimmel** [comment]
This is still reproducible for me on version 2.12 with https://github.com/illumos/illumos-gate (which is a fork of OpenSolaris). What did the fix involve? I am happy to test out a patch if desired.

**Comment by sitsofe** [comment]
@dankimmel It might be better to open an new issue about this if it can be reproduced with the latest git fio...
